language: cpp
compiler:
  - clang
  - gcc
env:
  - BUILDDIR=.
  - BUILDDIR=build

before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - gem install ronn
  - sudo apt-get install -qq thrift-compiler libthrift-dev libboost1.55-dev libclang-dev
  - "sudo sed -i -e 's/Cflags: /Cflags: -DHAVE_CONFIG_H /g' /usr/lib/pkgconfig/thrift*.pc" # Yep...
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; export CXX="g++-4.8"; fi

before_script:
  - mkdir -p "$BUILDDIR"
  - cd "$BUILDDIR"
script:
  - make -d -f "$OLDPWD/Makefile" all
  #- sudo make -f "$OLDPWD/Makefile" install-daemon
  #- sudo make -f "$OLDPWD/Makefile" install-vim
